### ISSUE TITLE
optional check importing file existing?

### ISSUE THREAD

**Issue by vcup** [jonkwheeler/tsconfig-replace-paths#37]
https://github.com/jonkwheeler/tsconfig-replace-paths/blob/71b7260099c3931f87c730c3a3e67d9d51016eba/src/index.ts#L175-L182
it'll check importing files, but i don't want this action...  
because i need import another module file extension name with `.js` instead `.ts`, even it doesn't exist.

**Comment by egmacke** [comment]
So I think I'm also seeing this issue. I'm building my project as an ESModule so all my import statements are written as `<path alias>/file.js` however, the resolution then fails as the source file that is being resolved is actually `file.ts`

This then fails to replace any imports.

@jonkwheeler I would be up for having a crack at resolving this if you want? Unless there are any reasons you have for not supporting this case?

**Comment by jonkwheeler** [comment]
Sure, give it a shot. If it works on my repos, I'll merge it.

**Comment by egmacke** [comment]
@jonkwheeler suggested fix here #39

**Comment by jonkwheeler** [comment]
Merged. I released Version 0.0.12

**Comment by egmacke** [comment]
@jonkwheeler Previous fix didn't quite solve the problem as it forgot to re-add the ext in the replacement - updated fix #41
